---
'on':
  push:
    paths:
      - .github/workflows/main.yaml
      - dist/main.js

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        cue-version:
          - 0.11.1
          - 0.10.1
          - 0.9.2
          - 0.8.2
          - 0.7.1
          - 0.6.0
          - 0.5.0
          - 0.4.3
          - 0.3.2
          - 0.2.2
          - 0.1.2
          - 0.0.15
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run colpal/setup-cue@${{ github.ref }}
        uses: ./
        with:
          cue-version: ${{ matrix.cue-version }}

      - run: cue version | grep -qF "$CUE_VERSION"
        env:
          CUE_VERSION: ${{ matrix.cue-version }}
