---
'on':
  push:
    paths:
      - .github/workflows/main.yaml
      - dist/main.js

jobs:
  main:
    strategy:
      matrix:
        cue-version:
          - 0.5.0-beta.2
          - 0.4.3
          - 0.3.2
          - 0.2.2
          - 0.1.2
          - 0.0.15
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
          - self-hosted
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Run colpal/setup-cue@${{ github.ref }}
        uses: ./
        with:
          cue-version: ${{ matrix.cue-version }}

      - run: cue version
