---
'on':
  push:
    paths:
      - .github/workflows/main.yaml
      - dist/main.js

jobs:
  main:
    strategy:
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - macos-11.0
          - macos-10.15
          - self-hosted
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Run colpal/setup-cue@${{ github.ref }}
        uses: ./
        with:
          cue-version: 0.3.0-beta.5

      - run: cue version
